#
# Analyze repository with PSRule for Azure
#

# Note:
# This workflow is designed to run in templated repositories to check Azure Infrastructure as Code.

# For PSRule for Azure documentation see:
# https://aka.ms/ps-rule-azure

# For action details see:
# https://aka.ms/ps-rule-action

name: Analyze Azure resources

# Run for main or PRs against main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bicep
        uses: anthony-c-martin/setup-bicep@v0.1
        continue-on-error: true
        with:
          # must be a version listed under https://github.com/Azure/bicep/releases
          version: v0.16.2

      # Run analysis by using the PSRule GitHub action.
      - name: Run PSRule analysis
        uses: microsoft/ps-rule@v2.8.1
        with:
          modules: PSRule.Rules.Azure
